version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3366:3366"
        networks:
            - symfony-network

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - symfony-network

    # Symfony apache project container
    www:
        build: docker/php
        container_name: symfony
        ports:
          - "8800:80"
        volumes:
            - /home/projects/symfony/docker/php/vhosts:/etc/apache2/sites-enabled
            - /home/projects/symfony/app:/var/www
        restart: always
        networks:
            - symfony-network

networks:
    symfony-network:

volumes:
    db-data:
