version: '3.8'

services:
    php:
        build: ./docker/php
        volumes:
            - ./home/projects/symfony/app:/var/www
        working_dir: /var/www
        expose:
            - 9001
        networks:
            - symfony-network

    nginx:
        image: nginx:alpine
        ports:
            - "8800:80"
        volumes:
            - /home/projects/symfony/docker/php/vhosts:/etc/apache2/sites-enabled
            - /home/projects/symfony/app:/var/www
        depends_on:
            - php
        networks:
            - symfony-network

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - symfony-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - symfony-network

volumes:
    db_data:

networks:
    symfony-network:
